export const MOVIEDATA='MOVIEDATA';
export const MOVIEDATA_ERROR='MOVIEDATA_ERROR';
export const PRODUCTDATA='PRODUCTDATA';
export const PRODUCTDATA_ERROR='PRODUCTDATA_ERROR';
export const ACTIONTEST='ACTIONTEST';